// Every user-visible string in the UI.
//
// This port is English-only by decision: there is no locale, no second catalogue and no
// translation layer. The lookup survives only because keeping the strings in one
// reviewable file beats scattering them across the ~500 places that use them.
export const strings = {
  'app.title': 'Tootega Cockpit',
  'about.cliUpToDate': 'Claude CLI is up to date.',
  'about.cliReleaseNotes': 'View release notes on GitHub',
  'spell.pt': 'Portuguese',
  'spell.en': 'English',
  'spell.add': 'Add to dictionary',
  'spell.ignore': 'Ignore',
  'spell.noSuggestions': 'No suggestions',
  'spell.loading': 'Checking…',
  'search.placeholder': 'Search…',
  'search.timeline': 'Timeline',
  'search.prompts': 'Prompts',
  'search.none': 'No results',
  'search.prev': 'Previous (Shift+Enter)',
  'search.next': 'Next (Enter)',
  'search.close': 'Close (Esc)',
  'onboarding.title': 'Get started',
  'onboarding.dismiss': 'Dismiss',
  'onboarding.cli': 'Install the Claude Code CLI',
  'onboarding.signin': 'Sign in to your Claude account',
  'onboarding.session': 'Open or create a context',
  'onboarding.voice': 'Try voice dictation and the spell-checker',
  'selection.included': 'Editor selection shared with Claude — click to exclude',
  'selection.excluded': 'Editor selection hidden — click to include',
  'about.cliOutdated': 'New version {0} available. Update with: claude update',
  'about.cliBelowMin':
    'This CLI is older than {0}. Interrupting the agent may silently fail. Update with: claude update',
  'about.update': 'Update',
  'about.install': 'Install',
  'about.install.tip': 'Claude CLI not found. Click to install.',
  'composer.placeholder': 'Ask Claude Code…  (Enter to send, Shift+Enter for newline)',
  'composer.send': 'Send',
  'composer.stop': 'Stop',
  'voice.start': 'Dictate (voice to text)',
  'voice.stop': 'Stop dictation',
  'voice.correcting': 'Correcting…',
  'voice.connecting': 'Connecting dictation… wait before speaking',
  'voicedict.open': 'Dictionaries (dictation & spell-checker)',
  'voicedict.title': 'Dictionaries',
  // Cofre de credenciais (TOTP 2FA)
  'creds.open': 'Credentials vault (2FA)',
  'remote.publish': 'Make this session visible on the remote client / app',
  'remote.active': 'Under Remote Control — click to turn it off (closes the terminal)',
  'remote.connecting': 'Connecting Remote Control — waiting for the session in the terminal',
  'remote.failed': 'Remote Control is down — see the terminal for the reason; click to reconnect',
  'creds.title': 'Credentials vault',
  'creds.enroll.intro':
    'Protect the vault with an authenticator app (Google Authenticator, Authy…). A code is required to add and to use any credential.',
  'creds.enroll.begin': 'Set up 2FA',
  'creds.enroll.scan': 'Scan the QR code in your authenticator, or enter the key manually:',
  'creds.enroll.manual': 'Manual setup key',
  'creds.enroll.confirm': 'Confirm',
  'creds.code': '6-digit code',
  'creds.code.hint': 'From your authenticator — required for every action.',
  'creds.code.invalid': 'Invalid code. Try the current one from your authenticator.',
  'creds.add': 'Add credential',
  'creds.add.action': 'Add',
  'creds.add.invalid': 'Name and value are required.',
  'creds.field.name': 'Name (e.g. AWS prod key)',
  'creds.field.username': 'User / identifier (optional)',
  'creds.field.value': 'Secret value',
  'creds.field.value.keep': 'New value (leave empty to keep)',
  'creds.field.note': 'Note (optional)',
  'creds.empty': 'No credentials yet.',
  'creds.use': 'Use',
  'creds.copy': 'Copy',
  'creds.use.hint': 'Releases the value (validates your code first).',
  'creds.edit': 'Edit',
  'creds.edit.save': 'Save',
  'creds.delete': 'Delete',
  'creds.delete.confirm': 'Confirm delete',
  'voicedict.desc':
    'Your personal dictionaries (per login): dictation terms/replacements, plus the spell-checker words you added or ignored.',
  'voicedict.account': 'Account for this dictionary',
  'voicedict.terms': 'Terms',
  'voicedict.terms.hint': 'Proper names and jargon to recognize and preserve (won\'t be "corrected").',
  'voicedict.terms.ph': 'e.g. Sāṃkhya',
  'voicedict.reps': 'Replacements',
  'voicedict.reps.hint': 'When dictation hears the left term, it writes the right one.',
  'voicedict.reps.from': 'heard',
  'voicedict.reps.to': 'written',
  'voicedict.reps.delete': '(removes)',
  'voicedict.add': 'Add',
  'voicedict.edit': 'Edit',
  'voicedict.remove': 'Remove',
  'voicedict.spell': 'Spell-checker dictionary',
  'voicedict.spell.hint': 'Words the spell-checker treats as correct (added/ignored). Click a word to edit, ✕ to remove.',
  'voicedict.spell.ph': 'e.g. Tootega',
  'voicedict.empty': 'Empty',
  'voicedict.save': 'Save',
  'plugins.title': 'Plugins',
  'plugins.desc': 'Search, install and remove Claude Code plugins',
  // The Skills panel (X2): the listing cost per skill, and which ones have fired
  'skills.title': 'Skills',
  'skills.desc': 'What each skill costs in the context and which ones are already loaded',
  'skills.loading': 'Reading the context…',
  'skills.none': 'No skill reported by the CLI in this session.',
  'skills.hint': 'Open a session and send a message first: the panel reads the running CLI.',
  // The totals at the top: metadata is MEASURED by the engine; the loaded body is estimated.
  'skills.tile.count': 'skills',
  'skills.tile.metadata': 'metadata',
  'skills.tile.active': 'loaded',
  'skills.tile.estimated': 'est.',
  'skills.tile.listedOf': '{0} of {1} listed',
  // Grupos por origem (valores reais do engine: projectSettings / userSettings / built-in).
  'skills.group.project': 'project',
  'skills.group.user': 'user',
  'skills.group.built-in': 'built-in',
  'skills.group.other': 'plugin',
  'skills.group.all': 'all',
  // The OBSERVATION axis — what is in the context — apart from the configuration dropdown.
  'skills.obs.active': 'loaded',
  'skills.obs.light': 'light',
  'skills.obs.resident': 'off · resident',
  'skills.legend.active': 'body loaded into the context of this session',
  'skills.legend.light': 'metadata only; it has not been triggered',
  'skills.legend.resident': 'off, but the body already loaded only leaves on a new session or /clear',
  'skills.legend.scope':
    'The dropdown is a Cockpit control, stored per workspace and applied when the CLI starts. Your ~/.claude/settings.json is not changed, and the CLI in the terminal is unaffected.',
  'skills.metaTokens': 'metadata {0} tk',
  'skills.activeTokens': '+{0} tk loaded (est.)',
  'skills.activeUnknown': 'loaded — the engine does not report the size',
  'skills.residentTokens': '{0} tk still in the context',
  'skills.residentUnknown': 'body still in the context (size not reported)',
  'skills.viaHook': 'loaded by a hook (recognised by the body)',
  'timeline.hookSkill': 'skill loaded by a hook: {0}',
  'timeline.hookContext': 'context injected by a hook',
  'timeline.engineNotice': 'engine warning',
  'timeline.compactAuto': 'context compacted (auto)',
  'timeline.compactManual': 'context compacted (manual)',
  'skills.hooks.title': 'hook context',
  'skills.hooks.note':
    'Text a hook injected into the context. It is not part of the skill listing, but it weighs the same.',
  'skills.hooks.tokens': '~{0} tk injected (est.)',
  'hookEvent.SessionStart': 'Fires when a session starts (or is resumed/forked).',
  'hookEvent.SessionEnd': 'Fires when the session ends.',
  'hookEvent.UserPromptSubmit': 'Fires on every prompt you submit.',
  'hookEvent.PreToolUse': 'Fires before a tool runs (can block it).',
  'hookEvent.PostToolUse': 'Fires after a tool finishes.',
  'hookEvent.Notification': 'Fires on agent notifications (e.g. awaiting input).',
  'hookEvent.Stop': 'Fires when the agent stops its turn.',
  'hookEvent.SubagentStop': 'Fires when a subagent stops.',
  'hookEvent.PreCompact': 'Fires before the context is compacted.',
  'hookEvent.DirectoryAdded': 'Fires after a working directory is added (/add-dir).',
  'hookEvent.unknown': 'Hook event: {0}',
  'skills.note.nameOnly': 'name only in the listing',
  'skills.note.slashOnly': 'out of the listing, /command still works',
  'skills.note.off': 'out of the listing',
  'skills.override': 'Listing',
  'skills.override.on': 'On (full)',
  'skills.override.name-only': 'Name only',
  'skills.override.user-invocable-only': 'Only /command',
  'skills.override.off': 'Off',
  'skills.overrideHelp':
    'Reduces what enters the context. Applies on the next CLI start (the session continues via --resume).',
  // Painel MCP (X4)
  'mcp.title': 'MCP',
  'mcp.desc': 'MCP servers: health, connection and the tools each one exposes',
  'mcp.servers': 'Servers',
  'mcp.count': '{0} servers · {1} tools',
  'mcp.checking': 'Checking server health…',
  'mcp.none': 'No MCP server configured.',
  'mcp.tools': '{0} tools',
  'mcp.noTools': 'Connected, but exposes no tool.',
  'mcp.notConfigured': 'Not configured (no URL)',
  'mcp.configError': 'Skipped by config validation: {0}',
  'mcp.stamp': 'Checked at {0}',
  'mcp.status.connected': 'Connected',
  'mcp.status.failed': 'Failed',
  'mcp.status.pending': 'Pending approval',
  'mcp.status.unknown': 'Unknown',
  'mcp.pendingHelp':
    'Declared in the repo’s .mcp.json but not approved yet — the CLI does not start it, and its tools are unavailable. Approve the server in the CLI (/mcp) to use it.',
  'plugins.searchPlaceholder': 'Search plugins…',
  'plugins.filter.all': 'All',
  'plugins.filter.installed': 'Installed',
  'plugins.filter.available': 'Available',
  'plugins.install': 'Install',
  'plugins.uninstall': 'Uninstall',
  'plugins.enable': 'Enable',
  'plugins.disable': 'Disable',
  'plugins.enabled': 'enabled',
  'plugins.disabled': 'disabled',
  'plugins.installs': 'Installs',
  'plugins.loading': 'Loading…',
  'plugins.empty': 'No plugins found.',
  'plugins.refresh': 'Refresh',
  'plugins.marketplaces': 'Marketplaces',
  'plugins.marketAdd': 'Add',
  'plugins.marketAddPlaceholder': 'Marketplace URL, GitHub repo or path…',
  'plugins.remove': 'Remove',
  'plugins.kind.skills': 'Skills',
  'plugins.kind.agents': 'Agents',
  'plugins.kind.commands': 'Commands',
  'plugins.kind.mcp': 'MCP',
  'plugins.kind.hooks': 'Hooks',
  'plugins.kind.mixed': 'Mixed',
  'composer.expandAll': 'Expand all cards in this context',
  'composer.collapseAll': 'Collapse all cards in this context',
  'composer.newSession': 'New session',
  'attach.remove': 'Remove attachment',
  'attach.view': 'View image',

  'activity.working': 'Working…',
  'activity.compacting': 'Compacting the context…',
  'activity.sent': 'Tokens sent',
  'activity.received': 'Tokens received',

  'tip.time': 'Time',
  'tip.chars': 'Characters',
  'tip.words': 'Words',
  'tip.images': 'Images',
  'tip.inputSize': 'Input',
  'tip.outputSize': 'Output',
  'tip.lines': 'Lines',
  'tip.duration': 'Duration',
  'tip.status': 'Status',
  'tip.id': 'ID',
  'tip.file': 'File',
  'tip.sess.created': 'Created',
  'tip.sess.updated': 'Updated',
  'tip.sess.messages': 'Messages',
  'tip.sess.user': 'Your messages',
  'tip.sess.assistant': 'Claude messages',
  'tip.sess.tools': 'Tool calls',
  'tip.sess.model': 'Model',
  'tip.sess.size': 'Size',

  'slash.menu.tip': 'Slash commands',
  'slash.menu.empty': 'No commands available',
  'slash.menu.loading': 'Researching commands…',
  'cmd.generic': 'Project or custom command.',
  'cmdcat.session': 'Session',
  'cmdcat.context': 'Context',
  'cmdcat.config': 'Configuration',
  'cmdcat.tools': 'Tools',
  'cmdcat.account': 'Account',
  'cmdcat.info': 'Info',
  'cmdcat.plugin': 'Plugins',
  'cmdcat.other': 'Other',
  'cmd.clear': 'Clear the conversation and free the context window.',
  'cmd.compact': 'Summarize the conversation to shrink context usage.',
  'cmd.context': 'Show a breakdown of what fills the context window.',
  'cmd.memory': 'View and edit project/user memory (CLAUDE.md).',
  'cmd.resume': 'Resume a previous session.',
  'cmd.model': 'Switch the active model.',
  'cmd.config': 'Open settings / configuration.',
  'cmd.permissions': 'Manage tool permissions and allow/deny rules.',
  'cmd.review': 'Review a pull request or the pending diff.',
  'cmd.codeReview': 'Review a pull request or the current branch (add "ultra" for a cloud review).',
  'cmd.init': 'Generate a CLAUDE.md for this codebase.',
  'cmd.mcp': 'Manage MCP servers and their tools.',
  'cmd.agents': 'List and configure subagents.',
  'cmd.hooks': 'View configured hooks and their triggers.',
  'cmd.login': 'Sign in to your Claude account.',
  'cmd.logout': 'Sign out of your Claude account.',
  'cmd.cost': 'Show token cost for this session.',
  'cmd.usage': 'Show plan usage and limits.',
  'cmd.status': 'Show CLI status (model, account, workspace).',
  'cmd.help': 'List available commands and help.',
  'cmd.doctor': 'Diagnose the installation and environment.',
  'tip.outChars': 'Output chars',
  'tip.estTokens': 'Est. tokens',
  'tip.thinking': 'Thinking chars',
  'tip.tools': 'Tool calls',
  'tip.tokensIn': 'Tokens in',
  'tip.tokensOut': 'Tokens out',
  'tip.cacheRead': 'Cache read',
  'tip.cacheCreate': 'Cache write',
  'tip.cacheHit': 'Cache hit',
  'tip.cost': 'Turn cost',

  'tip.ctx.context':
    'Context window: tokens loaded right now vs. the model limit. When it fills, older turns get compacted. Tokens come from the server; the limit is derived from the model ([1m]→1M, else 200K).',
  'tip.ctx.tokensSection': 'Tokens exchanged with the model this session.',
  'tip.ctx.input': 'Input tokens sent to the model this session (your messages, files, tool results).',
  'tip.ctx.output': 'Output tokens generated by the model this session (replies + thinking).',
  'tip.ctx.cacheSection': 'Prompt-cache reuse — the main driver of cost and latency.',
  'tip.ctx.hit':
    'Cache hit rate: share of input served from the prompt cache instead of being reprocessed. Higher = cheaper and faster.',
  'tip.ctx.cacheRead': 'Cache read: tokens reused from the prompt cache (billed at a fraction of input).',
  'tip.ctx.cacheWrite': 'Cache write: tokens written into the prompt cache for later reuse.',
  'tip.ctx.savings':
    'Estimated savings from the prompt cache: what you would have paid if those tokens were billed at the full input rate instead of the cache-read rate.',
  'tip.ctx.duration': 'Time elapsed since this session started (from the first CLI init event).',
  'tip.ctx.cacheLife':
    'Time until the prompt cache (1h) expires. Each request restarts the window. With "keep alive" checked, Cockpit refreshes it before it expires — even with the context closed — to avoid re-paying the cache write. It never revives an already-expired cache. The age comes from the local clock; the 1h TTL is an assumption (the CLI does not report the real expiry).',
  'tip.ctx.costEstimate':
    'Estimated — the CLI has not yet reported a confirmed cost for this session. With "~" it is a price-table estimate; without "~" it is the CLI\'s real cost (matches /cost).',
  'tip.ctx.toolAcceptance':
    'Share of tool permission requests you allowed vs. denied this session, per tool.',
  'tip.ctx.activity': 'Counters that survive reopening/resuming the context.',
  'tip.ctx.peak': 'Largest context size reached this session (in tokens), with the cache size (create + read) at that peak.',
  'tip.ctx.compactions':
    'How many times the context was condensed between turns to free up room (detected when the total shrinks).',
  'tip.ctx.resets':
    'How many times the prompt cache expired from idleness (>1h) and the prefix had to be re-written, plus the cost re-paid.',
  'tip.ctx.denials':
    'Tool requests denied this session — by you, in the modal, or by the CLI itself (“auto” chip) — newest first, with the reason when given. Access-control audit.',
  'tip.ctx.denials.engine':
    'Denied by the CLI, not by you: an auto-mode rule (or a missing permission) blocked the call.',
  // Hint provenance footer (colored chips).
  'meta.origin.label': 'Source',
  'meta.origin.server': 'Server (via CLI)',
  'meta.origin.local': 'Local',
  'meta.origin.computed': 'Computed',
  'meta.origin.estimate': 'Estimated',
  'meta.origin.cli': 'CLI',
  'meta.conf.label': 'Confidence',
  'meta.conf.high': 'High',
  'meta.conf.medium': 'Medium',
  'meta.conf.low': 'Low',

  'tip.ctrl.engine':
    'Which program answers: Claude Code (your Anthropic account) or Tootega Code (a local model through the TootegaEngine server — no account, no cost, nothing leaves the machine). Switching restarts the engine; the conversation is kept.',
  'tip.ctrl.model':
    'Model running this session. "Default" follows your settings; pick a specific Opus/Sonnet/Haiku or enter a custom id. Applies on next message.',
  'tip.ctrl.effort':
    'Reasoning effort: higher = deeper thinking, more tokens and latency; lower = faster and cheaper. Applies on next message.',
  'tip.ctrl.permission':
    'Permission mode: how tool calls are approved — ask each time, auto-accept edits, or bypass prompts. Applies on next message.',
  'tip.ctrl.agents':
    'Allow the agent to spawn subagents (Task) and workflows. These run extra parallel agents and can burn a lot of tokens. Turn off to save tokens. Applies on next message.',

  'role.user': 'You',
  'role.assistant': 'Claude',
  'turn.canceled': 'Canceled',
  'role.system': 'System',

  'thinking.show': 'Show thinking',
  'thinking.hide': 'Hide thinking',

  'tool.input': 'Input',
  'tool.output': 'Output',
  'tool.sandboxDenied': 'Blocked by the sandbox',
  'tool.command': 'Command',
  'tool.running': 'Running…',
  'tool.error': 'Error',
  'tool.view': 'View',
  'tool.endConversation': 'The agent ended the conversation',
  'tool.subagent': 'Subagent output',

  'status.idle': 'Idle',
  'status.busy': 'Working…',
  'background.title': 'Running in the background',
  'status.model': 'Model',
  'status.mode': 'Mode',
  'status.cliMissing': 'CLI not found',
  'status.connecting': 'Connecting…',
  'status.idle.desc': 'Ready. Send a message to start.',
  'status.busy.desc': 'The agent is working — reading, editing or running tools.',
  'status.cliMissing.desc': 'The Claude Code CLI was not found on your PATH. Install it or set the path in settings.',

  'tip.sessions.title': 'Conversations',
  'tip.sessions.desc': 'Browse, resume or delete past sessions saved for this folder.',
  'tip.new.title': 'New session',
  'tip.new.desc': 'Open a fresh conversation in a new tab. Runs in parallel with the others.',
  'tip.deleteAll.title': 'Delete all sessions',
  'tip.deleteAll.desc': 'Permanently delete every saved session in this folder from disk.',
  'tip.settings.title': 'Settings',
  'tip.settings.desc': 'Open Tootega Cockpit settings: model, effort, permissions, language and more.',
  'tip.login.title': 'Sign in',
  'tip.login.desc': 'Sign in to Claude in a terminal (browser OAuth via the CLI). Credentials stay in the CLI.',
  'tip.logout.title': 'Sign out',
  'tip.logout.desc': 'Sign out from Claude (runs `claude auth logout` in a terminal).',
  'tip.usage.desc': 'Account and consumption: rate limits (5h / weekly), plan, and what is driving your usage. Fetched live on click.',

  'usage.button': 'Usage',
  'usage.title': 'Account & Usage',
  'usage.loading': 'Fetching usage…',
  'usage.account': 'Account',
  'usage.authMethod': 'Auth method',
  'usage.email': 'Email',
  'usage.org': 'Organization',
  'usage.plan': 'Plan',
  'usage.session': 'Session',
  'usage.session.src': 'from statusline',
  'usage.fastMode': 'Fast mode',
  'usage.sessionKind': 'Session kind',
  'usage.sessionKind.interactive': 'Interactive',
  'usage.sessionKind.attached': 'Attached',
  'usage.sessionKind.unattended': 'Unattended',
  'usage.modelLabel': 'Model',
  'usage.effortLevel': 'Effort',
  'usage.outputStyle': 'Output style',
  'common.on': 'On',
  'common.off': 'Off',
  'usage.loginExpires': 'Login valid for',
  'usage.loginExpiringSoon':
    'Your login expires in {0}. Run /login to re-authenticate — an expired login interrupts long or background sessions.',
  'usage.notLoggedIn': 'Not signed in.',
  'usage.usage': 'Usage',
  'usage.currentSession': 'Current session',
  'usage.weeklyAll': 'Weekly · all models',
  'usage.weeklyModel': 'Weekly · {0}',
  'usage.manage': 'Manage usage on claude.ai',
  'usage.na': 'n/a',
  'usage.resetsIn': 'Resets in {0}',
  'usage.contributing': "What's contributing to your limits usage?",
  'usage.day': 'Day',
  'usage.week': 'Week',
  'usage.approx':
    'Approximate, based on local sessions on this machine — does not include other devices or claude.ai.',
  'usage.noData': 'No usage recorded in this window.',
  'usage.i.context': '{0}% of your usage was at >150k context',
  'usage.i.context.desc':
    'Longer sessions are more expensive even when cached. /compact mid-task, /clear when switching to new tasks.',
  'usage.i.subagents': '{0}% of your usage came from subagents',
  'usage.i.subagents.desc':
    'Each subagent runs its own requests. Be deliberate about spawning them — and consider a cheaper model for simpler subagents.',
  'usage.i.topSub': '{0}% of your usage came from subagents under "{1}"',
  'usage.i.topSub.desc':
    'If this runs frequently, consider configuring its subagents with a cheaper model or tightening their prompts.',
  'usage.subagents': 'Subagents',
  'usage.pctOfUsage': '% of usage',
  'usage.attribution': 'Where your tokens went',
  'usage.i.cache': '{0}% cache hit rate',
  'usage.i.cache.desc':
    'Share of context read back from cache instead of rewritten. Higher is better: cached reads cost a fraction of the price.',
  'usage.attr.byTool': 'Context injected per tool',
  'usage.attr.tool.calls': '{0} calls · ~{1} tok',
  'usage.attr.note':
    'Tokens from tool results, estimated at ~4 characters per token. MCP servers are grouped together.',
  'usage.generatedAt': 'Fetched at {0}',
  'usage.badge.live': 'live',
  'usage.badge.est': 'estimate',
  'usage.est.note':
    'Local estimate — exact account limits come from the CLI statusline (not reachable headless). Enable live tracking to capture them.',
  'usage.est.waiting':
    'Local estimate — real account limits appear after Claude refreshes the statusline (use the CLI once).',
  'usage.est.reason': 'Real usage unavailable: {0}.',
  'usage.enableTracking': 'Enable live tracking',
  'usage.breakdown': 'Breakdown (7 days)',
  'usage.breakdown.byModel': 'By model',
  'usage.breakdown.bySource': 'By source',
  'usage.breakdown.note': 'Table estimate from this machine\'s sessions — this machine only, does not include other devices. The USD figure is the equivalent API price: on a subscription you are not charged this.',
  'usage.slice.newTokens': '{0} new tok',
  'usage.slice.cacheRead': '+ {0} tok cache read',
  'usage.tokens': 'Tokens (global)',
  'usage.tokens.badge': 'all-time',
  'usage.tokens.sent': 'Sent',
  'usage.tokens.received': 'Received',
  'usage.tokens.total': 'Total',
  'usage.tokens.byDay': 'By day',
  'usage.tokens.note': 'All contexts and VSCode windows on this machine, counted from local transcripts.',
  'usage.source.main': 'Main',
  'usage.source.subagent': 'Subagents',
  'usage.otel': 'Telemetry (OTEL)',
  'usage.otel.live': 'live',
  'usage.otel.loc': 'Lines of code (+/−)',
  'usage.otel.costByModel': 'Real cost by model',
  'usage.otel.locByModel': 'Lines by model',
  'usage.otel.lines': 'lines',
  'usage.otel.sessions': 'Sessions',
  'usage.otel.commits': 'Commits',
  'usage.otel.prs': 'Pull requests',
  'usage.otel.decisions': 'Edit decisions',
  'usage.otel.workflows': 'Workflow runs',
  'tip.stop.title': 'Interrupt',
  'tip.stop.desc': 'Stop the agent now. The current turn ends and the session stays open.',

  'controls.model': 'Model',
  'controls.model.remove': 'Remove model',
  'controls.context': 'Context',
  'controls.price': 'Price',
  'controls.usage': 'Usage',
  'tip.effort.est': 'Estimated relative token consumption per effort level (high = 1x). Approximate — Anthropic does not publish an official factor.',
  'controls.effort': 'Effort',
  'controls.engine': 'Engine',
  'engine.claude': 'Claude Code',
  'engine.tootega': 'Tootega Code',
  'controls.permission': 'Permission',
  'controls.agents': 'Agents & workflows',
  'controls.applies': 'Applied on the next message (restarts the session).',
  // The CLI renamed the "default" mode to "Manual" (2.1.131). The internal value
  // is still 'default' (= no --permission-mode flag), compatible with older CLIs.
  'perm.default': 'Manual',
  'perm.plan': 'Plan',
  'perm.acceptEdits': 'Accept edits',
  'perm.auto': 'Auto',
  'perm.dontAsk': "Don't ask",
  'perm.bypassPermissions': 'Bypass',
  'common.copy': 'Copy',
  'common.save': 'Save',
  'tabs.new': 'New conversation',
  'tabs.close': 'Close',
  'tabs.untitled': 'Conversation',
  'todos.title': 'Tasks',
  'todos.expand': 'Expand',
  'todos.collapse': 'Collapse',
  'tip.tasks.title': 'Tasks',
  'tip.tasks.desc': "Show or hide the agent's live task list. Drag it anywhere over the chat.",
  'scroll.bottom': 'Scroll to bottom',
  'export.link': '⬇ Export conversation (Markdown)',
  'export.direct': 'Direct export (timeline)',
  'export.ai': '✨ Generate document with AI',
  'export.ai.note': '⚠ Spends subscription tokens · uses the context model {0} and effort {1}',
  'export.docTitle': 'Conversation',
  'export.generatedAt': 'Exported on {0}',
  'export.you': 'You',
  'export.assistant': 'Claude',
  'export.thinking': 'Reasoning',
  'sessions.search': 'Search sessions…',
  'sessions.today': 'Today',
  'sessions.yesterday': 'Yesterday',
  'sessions.week': 'Last 7 days',
  'sessions.older': 'Older',
  'sessions.rename': 'Rename',
  'sessions.reload': 'Reload view (fix gray/blank panel)',
  'sessions.remote': 'Remote control (follow & interact from your phone)',
  'sessions.openHint': 'Click to open in its tab (or a new one).',
  'model.default': 'Default',
  'effort.default': 'Default',
  'effort.low': 'Low',
  'effort.medium': 'Medium',
  'effort.high': 'High',
  'effort.xhigh': 'X-High',
  'effort.max': 'Max',

  'stats.title': 'Usage',
  'stats.usage': 'Account usage',
  'stats.usageLimits': 'Usage limits',
  'stats.context': 'Context window',
  'stats.clear': 'Clear',
  'stats.clear.tip': 'Clear the context (start a fresh conversation in this tab)',
  'stats.compact': 'Compact',
  'stats.compact.tip': 'Compact the context (/compact) to free up space',
  'stats.context.used': '{0} / {1} tokens',
  'stats.context.remaining': '{0} tokens left',
  'stats.context.breakdown': 'Breakdown',
  'stats.cache': 'Cache',
  'stats.cache.hitRate': 'Hit rate',
  'stats.cache.read': 'Read',
  'stats.cache.write': 'Write',
  'stats.cache.savings': 'Est. savings',
  'stats.cache.life': 'Cache life',
  'stats.cache.life.left': '{0} left',
  'stats.cache.life.expired': 'expired',
  'stats.cache.keepAlive': 'Keep cache alive (refresh before 1h)',
  'stats.cost': 'Cost',
  'stats.cost.session': 'Session',
  'stats.cost.lastTurn': 'Last turn',
  'stats.cost.estimate': 'estimated',
  'stats.tokens': 'Tokens',
  'stats.tokens.input': 'Input',
  'stats.tokens.output': 'Output',
  'stats.session.duration': 'Duration',
  'stats.tools.acceptance': 'Tool acceptance',
  'stats.activity': 'Session activity',
  'stats.activity.turns': 'Turns',
  'stats.activity.peak': 'Peak context',
  'stats.activity.compactions': 'Compactions',
  'stats.activity.resets': 'Cache resets',
  'stats.activity.recache': 'Re-cache paid',
  'stats.denials': 'Recent denials',
  'stats.denials.engine': 'auto',
  'alert.compacted': 'Context compacted ({0}): {1} tokens condensed to free up room.',

  'ctxPanel.title': 'Context',
  'ctxPanel.contexts': 'Saved contexts',
  'ctxPanel.noStats': 'No context stats yet — send a message to start.',
  'ctxPanel.openFolder': 'Open folder in file manager',

  'folder.title': 'Conversation folder',
  'folder.reveal': 'Open this folder in the file manager',
  'folder.change': 'Change…',
  'folder.changeHint': 'Run this conversation in another folder',
  'folder.changeBusy': 'Wait for the current turn to finish',

  'hub.openEditor': 'Open chat',
  'tip.context.title': 'Context panel',
  'tip.context.desc': 'Context window, session controls and saved contexts.',
  'stats.limits': 'Account limits',
  'stats.limits.fiveHour': 'Current session',
  'stats.limits.sevenDay': 'Weekly limit',
  'stats.limits.resetsAt': 'resets {0}',
  'stats.limits.status.ok': 'OK',
  'stats.limits.status.warning': 'near limit',
  'stats.limits.status.rejected': 'limit reached',
  'stats.limits.unavailable': 'Not reported by the CLI yet.',
  'stats.limits.local': 'Approximate · estimated from local sessions.',
  'stats.limits.realNote': 'Account · live from the CLI statusline.',
  'stats.limits.streamNote': 'Account · live from the engine stream (5h; 7-day near limit).',

  'alert.contextHigh': 'Context is almost full — compaction may happen soon.',
  'alert.limitHigh': 'You are close to your plan limit.',

  'permission.title': 'Permission required',
  'permission.body': 'Claude wants to use {0}.',
  'permission.allow': 'Allow',
  'permission.allowAlways': 'Always allow',
  'permission.alwaysEdits': 'Always allow edits',
  'permission.deny': 'Deny',
  'permission.openDiff': 'Open diff in editor',
  'permission.shortcut': 'Ctrl+Enter to allow · Esc to deny',
  'permission.planTitle': 'Plan ready for review',
  'permission.planSubtitle': 'Approve to start executing',
  'permission.approvePlan': 'Approve & run',
  'permission.keepPlanning': 'Keep planning',
  'permission.planEdit': 'Edit',
  'permission.planPreview': 'Preview',
  'permission.invisibleChars':
    'This command contains characters that do not show up on screen (marked below). Read it before approving.',
  'permission.planMaximize': 'Maximize',
  'permission.planRestore': 'Restore',
  'permission.planSendNotes': 'Keep planning (send my notes)',

  'ask.title': 'Claude has a question',
  'ask.answered': 'Question answered',
  'ask.submit': 'Submit',
  'ask.other': 'Other…',
  'ask.otherPlaceholder': 'Type your answer',
  'ask.multiHint': 'Select one or more',
  'ask.notesLabel': 'Add to this answer (optional)',
  'ask.notesPlaceholder': 'Context, a constraint, an exception to the choice above…',
  'ask.notesCard': 'Added:',
  'ask.notesHint': 'Enter sends · Shift+Enter for a new line',

  'empty.welcome': 'Start a conversation with Claude Code.',
  'empty.cliHint': 'The Claude Code CLI must be installed and authenticated.',

  'cli.missing.title': 'Claude Code CLI not found',
  'cli.missing.desc':
    'The Cockpit drives the official Claude Code CLI — it is not bundled. Install it, then re-check. You still authenticate with your own Claude account.',
  'cli.install': 'Install Claude Code',
  'cli.recheck': 'Re-check',
  'cli.docs': 'Documentation',
  'cli.auth.title': 'Sign in to Claude',
  'cli.auth.desc':
    "The CLI isn't authenticated. Sign in opens the official Claude Code login (browser OAuth) in a terminal — your credentials stay in the CLI, never in the Cockpit.",
  'cli.login': 'Sign in',

  'group.aliases': 'Aliases (latest)',
  'group.versions': 'Versions',
  'group.context1m': '1M context',

  'common.close': 'Close',
  'sessions.title': 'Sessions',
  'sessions.empty': 'No saved sessions in this folder.',
  'sessions.messages': 'msgs',
  'sessions.folder': 'Folder',
  'sessions.delete': 'Delete session',
  'sessions.deleteAll': 'Delete all',
  'session.untitled': '(untitled)',
  'confirm.delete.title': 'Delete session?',
  'confirm.delete.body': 'This permanently deletes "{0}" from disk and cannot be undone.',
  'confirm.delete.action': 'Delete',
  'confirm.deleteAll.title': 'Delete all sessions?',
  'confirm.deleteAll.body': 'This permanently deletes all {0} sessions in this folder from disk and cannot be undone.',
  'confirm.deleteAll.action': 'Delete all',
  'confirm.rewind.title': 'Rewind to here?',
  'confirm.rewind.body': 'This removes this prompt and everything after it from the conversation and cannot be undone.',
  'confirm.rewind.action': 'Rewind',
  'confirm.effort.title': 'Effort below repo minimum',
  'confirm.effort.body': 'This repo requires at least "{1}" effort, but the current effort is "{0}". Send anyway, or cancel and raise the effort first?',
  'confirm.effort.action': 'Send anyway',
  'rewind.title': 'Rewind to here (removes this prompt and everything after)',
  'bubble.showMore': 'Show more',
  'bubble.showLess': 'Show less',
  'confirm.cancel': 'Cancel',
};

export type Strings = typeof strings;
